<?php

namespace TW\neloBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

	public function findAllProducts($id){
		$em = $this->getEntityManager();
		$repository = $em->getrepository('TWneloBundle:Category');
		$category = $repository->find($id);

		$products = $category->getProducts();

		return $products;
	}
}
