<?php

namespace TW\neloBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FacilitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacilitiesRepository extends EntityRepository
{
}
