<?php

namespace TW\neloBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeRepository extends EntityRepository{

		public function findAllWithId(){
			$em = $this->getEntityManager();
			$repository = $em->getRepository('TWneloBundle:Type');
			$query = $repository->createQueryBuilder('t')->getQuery();

			return $query->getResult();
		}

}
