security:
    encoders:
        TW\neloBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: TWneloBundle:User, property: username }
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:: login
                check_path:: login_check
                target: /home
                failure_forward: true
                failure_path: /home
            form_login: ~
            logout: 
                path: /logout
                target: /home

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/rooms/booking/, roles: [ ROLE_USER, ROLE_ADMIN] }
        - { path: ^/rooms/booking$, roles: [ ROLE_USER, ROLE_ADMIN] }
        - { path: ^/admin$, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
